version: '3.8'

services:
  django:
    build: './app'
    container_name: "django"
    networks:
      - default
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./app/static-root:/app/staticfiles
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgresadmin
  db:
    image: postgres:latest
    container_name: "postgresDB"
    restart: always
    expose:
      - "5432"
    volumes:
      - type: "bind"
        source: "./db"
        target: "/var/lib/postgres/data"
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgresadmin
    networks:
      - default

  nginx:
    build: "./nginx"
    container_name: "nginx"
    networks:
      - default
    depends_on:
      - django
    ports:
      - 80:80
    volumes:
      - ./app/static-root:/app/staticfiles
    